In [1]:
import pandas as pd
import os
usuario = os.getlogin()

In [2]:
import pandas as pd

sheet_id = "1maRNGDuU9rEFWZLgMdhJS1waAnJxl6ENntm-nyD0tq8"
gid = "1765182479"

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}"

base_an = pd.read_csv(url)

In [3]:
base = pd.read_excel(fr"C:\Users\{usuario}\Downloads\UnidadesIMB_CS!_v2 (1).xlsx",sheet_name="Sheet 1")
clues = pd.read_parquet(fr"C:\Users\{usuario}\IMSS-BIENESTAR\División de Procesamiento de información - Repositorio de Datos\CLUES\clues.parquet")

In [4]:
base_an = base_an.drop(columns=["nombre_de_la_unidad"])

In [5]:
base_an

,fecha_registro,tipo_registro,entidad,usuario_nombre,usuario_email,clues_imb,categoria_gerencial_ampliada,internet,consultorios_habilitados,consultorio,pregunta,valor,turno
0,1/07/2026 17:56:29,unidad,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000025,NaN,True,NaN,NaN,internet,NaN,NaN
1,1/07/2026 17:56:39,respuesta,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000025,NaN,NaN,NaN,1.0,turno_consultorio_1,Ambos,NaN
2,9/07/2026 15:35:53,unidad,BAJA CALIFORNIA,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BCIMB000092,NaN,False,NaN,NaN,internet,NaN,NaN
3,3/07/2026 10:26:07,unidad,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000136,NaN,True,NaN,NaN,internet,NaN,NaN
4,3/07/2026 10:28:10,respuesta,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000136,NaN,NaN,NaN,1.0,turno_consultorio_1,Matutino,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43243,17/07/2026 14:57:11,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,contenedor_de_jabon_liquido_consultorio_1,0,NaN
43244,17/07/2026 14:57:18,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,contenedor_de_toallas_desechables_consultorio_1,0,NaN
43245,17/07/2026 14:57:29,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,contenedor_rigido_para_rpbi_consultorio_1,0,NaN
43246,17/07/2026 14:57:36,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,cubeta_de_acero_inoxidable_y_bolsa_consultorio_1,0,NaN
43247,17/07/2026 14:57:40,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,escritorio_medico_consultorio_1,1,NaN

In [6]:
base_an.columns.tolist()

['fecha_registro',
 'tipo_registro',
 'entidad',
 'usuario_nombre',
 'usuario_email',
 'clues_imb',
 'categoria_gerencial_ampliada',
 'internet',
 'consultorios_habilitados',
 'consultorio',
 'pregunta',
 'valor',
 'turno']

In [7]:
col = ["clues_imb"]
base = base[col]

In [25]:
base

,clues_imb,entidad,nombre_de_la_unidad
0,BCIMB000051,BAJA CALIFORNIA,COLONIA LOMA LINDA
1,BCIMB000092,BAJA CALIFORNIA,FRACCIONAMIENTO MAR
2,BCIMB000162,BAJA CALIFORNIA,ISLA DE CEDROS
3,BCIMB000186,BAJA CALIFORNIA,LA MISIÓN
4,BCIMB000191,BAJA CALIFORNIA,REAL DEL CASTILLO
...,...,...,...
1267,VZIMB008840,VERACRUZ DE IGNACIO DE LA LLAVE,C.S. LA CUESTA
1268,ZSIMB000446,ZACATECAS,CENTRO DE SALUD GUADALUPE
1269,ZSIMB001636,ZACATECAS,CENTRO DE SALUD COL. GONZÁLEZ ORTEGA
1270,ZSIMB001641,ZACATECAS,CENTRO DE SALUD ZACATECAS
1271,ZSIMB002102,ZACATECAS,CENTRO DE SALUD MARTÍNEZ DOMÍNGUEZ

In [8]:
base = base.merge(
    clues[["clues_imb", "entidad",'nombre_de_la_unidad']],
    on="clues_imb",
    how="left"
)

In [9]:
base_an = base_an.merge(
    clues[["clues_imb",'nombre_de_la_unidad']],
    on="clues_imb",
    how="left"
)

In [10]:
base_an

,fecha_registro,tipo_registro,entidad,usuario_nombre,usuario_email,clues_imb,categoria_gerencial_ampliada,internet,consultorios_habilitados,consultorio,pregunta,valor,turno,nombre_de_la_unidad
0,1/07/2026 17:56:29,unidad,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000025,NaN,True,NaN,NaN,internet,NaN,NaN,CENTRO DE SALUD PUERTO ADOLFO LÓPEZ MATEOS
1,1/07/2026 17:56:39,respuesta,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000025,NaN,NaN,NaN,1.0,turno_consultorio_1,Ambos,NaN,CENTRO DE SALUD PUERTO ADOLFO LÓPEZ MATEOS
2,9/07/2026 15:35:53,unidad,BAJA CALIFORNIA,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BCIMB000092,NaN,False,NaN,NaN,internet,NaN,NaN,FRACCIONAMIENTO MAR
3,3/07/2026 10:26:07,unidad,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000136,NaN,True,NaN,NaN,internet,NaN,NaN,CENTRO DE SALUD BAHÍA TORTUGAS
4,3/07/2026 10:28:10,respuesta,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000136,NaN,NaN,NaN,1.0,turno_consultorio_1,Matutino,NaN,CENTRO DE SALUD BAHÍA TORTUGAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43243,17/07/2026 14:57:11,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,contenedor_de_jabon_liquido_consultorio_1,0,NaN,SAN JUAN CHAPULTEPEC
43244,17/07/2026 14:57:18,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,contenedor_de_toallas_desechables_consultorio_1,0,NaN,SAN JUAN CHAPULTEPEC
43245,17/07/2026 14:57:29,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,contenedor_rigido_para_rpbi_consultorio_1,0,NaN,SAN JUAN CHAPULTEPEC
43246,17/07/2026 14:57:36,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,cubeta_de_acero_inoxidable_y_bolsa_consultorio_1,0,NaN,SAN JUAN CHAPULTEPEC
43247,17/07/2026 14:57:40,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,escritorio_medico_consultorio_1,1,NaN,SAN JUAN CHAPULTEPEC

In [11]:
b = pd.read_excel(fr"C:\Users\{usuario}\Downloads\UM_IMB_SUS.xlsx",sheet_name="Hoja2")

In [12]:
b = b.drop(index=[3])
b = b.drop(columns=['Unnamed: 1'])
b = b.rename(columns={
   'CLUES' : 'preguntas',
})

In [13]:
base_an

,fecha_registro,tipo_registro,entidad,usuario_nombre,usuario_email,clues_imb,categoria_gerencial_ampliada,internet,consultorios_habilitados,consultorio,pregunta,valor,turno,nombre_de_la_unidad
0,1/07/2026 17:56:29,unidad,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000025,NaN,True,NaN,NaN,internet,NaN,NaN,CENTRO DE SALUD PUERTO ADOLFO LÓPEZ MATEOS
1,1/07/2026 17:56:39,respuesta,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000025,NaN,NaN,NaN,1.0,turno_consultorio_1,Ambos,NaN,CENTRO DE SALUD PUERTO ADOLFO LÓPEZ MATEOS
2,9/07/2026 15:35:53,unidad,BAJA CALIFORNIA,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BCIMB000092,NaN,False,NaN,NaN,internet,NaN,NaN,FRACCIONAMIENTO MAR
3,3/07/2026 10:26:07,unidad,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000136,NaN,True,NaN,NaN,internet,NaN,NaN,CENTRO DE SALUD BAHÍA TORTUGAS
4,3/07/2026 10:28:10,respuesta,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000136,NaN,NaN,NaN,1.0,turno_consultorio_1,Matutino,NaN,CENTRO DE SALUD BAHÍA TORTUGAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43243,17/07/2026 14:57:11,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,contenedor_de_jabon_liquido_consultorio_1,0,NaN,SAN JUAN CHAPULTEPEC
43244,17/07/2026 14:57:18,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,contenedor_de_toallas_desechables_consultorio_1,0,NaN,SAN JUAN CHAPULTEPEC
43245,17/07/2026 14:57:29,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,contenedor_rigido_para_rpbi_consultorio_1,0,NaN,SAN JUAN CHAPULTEPEC
43246,17/07/2026 14:57:36,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,cubeta_de_acero_inoxidable_y_bolsa_consultorio_1,0,NaN,SAN JUAN CHAPULTEPEC
43247,17/07/2026 14:57:40,respuesta,OAXACA,Raymundo Barrea Hernandez,cs.sanjuanchapultepec@gmail.com,OCIMB000893,NaN,NaN,NaN,1.0,escritorio_medico_consultorio_1,1,NaN,SAN JUAN CHAPULTEPEC

In [14]:
b

                                            preguntas
0                                 Nombre de la Unidad
1                  Consultorios generales habilitados
2                  Consultorios generales disponibles
4                                   Equipo de cómputo
5                                            Internet
6                                     Banco de altura
7                                     Banco giratorio
8                Báscula electrónica  con estadímetro
9                      Báscula pesabebés electrónica
10                Mesa para colocar báscula pesabebés
11                           Bote sanitario con pedal
12    Caja portalaminilla de plástico con separadores
13                            Carta Snellen con marco
14                Charola de Mayo de acero inoxidable
15                                      Cinta métrica
16                        Contenedor de jabón líquido
17                  Contenedor de toallas desechables
18                        Contenedor rígido para RPBI
19                 Cubeta de acero inoxidable y bolsa
20                                  Escritorio médico
21                                  Esfigmomanómetro
22                                    Espejo vestidor
23                                 Espejos vaginales
24                             Estadímetro pediátrico
25                         Estetoscopio cápsula doble
26       Estetoscopio Pinard o doppler fetal portátil
27  Guarda de medicamentos, materiales o instrumental
28                           Guardarropa con perchero
29             Lámpara de examinación  de pie rodable
30                                            Lavabo
31                                  Martillo percusor
32                   Mesa de Mayo de acero inoxidable
33                                       Mesa Pasteur
34                    Mesa universal para Exploración
35                                          Otoscopio
36                                 Oximetro de pulso
37        Porta cubeta rodable con protector de hule
38             Porta rollo para papel Kraft o sábanas
39                             Silla para el paciente
40                          Silla para el acompañante
41                  Sillón giratorio de respaldo bajo
42  Termo congelante integrado para transporte y c...
43                  Paquetes refrigerantes para termo
44                              Termómetro de vástago
45                                Termómetro digital
46                                       Tijera recta
47             Torundera con tapa de acero Inoxidable
48                        Vaso contenedor  de vacunas

In [15]:
import pandas as pd

# Información de la unidad
unidad = (
    base_an[base_an["tipo_registro"] == "unidad"][
        [
            "entidad",
            "clues_imb",
            "nombre_de_la_unidad",
            "internet",
            "consultorios_habilitados",
        ]
    ]
    .drop_duplicates("clues_imb")
)

# Información por consultorio
respuesta = base_an[base_an["tipo_registro"] == "respuesta"].copy()

# Quitar el sufijo _1, _2, _3...
respuesta["pregunta"] = respuesta["pregunta"].str.replace(
    r"_\d+$", "", regex=True
)

# Convertir preguntas en columnas
pivot = respuesta.pivot_table(
    index=["entidad", "clues_imb", "consultorio"],
    columns="pregunta",
    values="valor",
    aggfunc="first"
).reset_index()

pivot.columns.name = None

# Unir con la información de la unidad
resultado = pivot.merge(
    unidad,
    on=["entidad", "clues_imb"],
    how="left"
)

# Reordenar columnas
columnas_fijas = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
]

columnas_preguntas = [
    c for c in resultado.columns if c not in columnas_fijas
]

resultado = resultado[columnas_fijas + sorted(columnas_preguntas)]

In [16]:
resultado

,entidad,clues_imb,nombre_de_la_unidad,internet,consultorios_habilitados,consultorio,banco_de_altura_consultorio,banco_giratorio_consultorio,bascula_electronica__con_estadimetro_consultorio,bascula_pesabebes_electronica_consultorio,...,silla_para_el_acompanante_consultorio,silla_para_el_paciente_consultorio,sillon_giratorio_de_respaldo_bajo_consultorio,termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio,termometro_de_vastago_consultorio,termometro_digital_consultorio,tijera_recta_consultorio,torundera_con_tapa_de_acero_inoxidable_consultorio,turno_consultorio,vaso_contenedor__de_vacunas_consultorio
0,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,False,NaN,1.0,1,0,0,0,...,1,1,1,NaN,NaN,NaN,NaN,NaN,Matutino,NaN
1,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,False,NaN,2.0,1,1,1,0,...,1,1,1,NaN,NaN,NaN,NaN,NaN,Matutino,NaN
2,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,False,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matutino,NaN
3,BAJA CALIFORNIA,BCIMB000302,HÉROES DE LA INDEPENDENCIA,True,1.0,1.0,0,1,0,0,...,1,1,1,0,0,0,1,1,Matutino,0
4,BAJA CALIFORNIA,BCIMB000314,VALLE DE LA TRINIDAD,True,2.0,1.0,1,1,1,1,...,1,1,1,0,0,0,0,1,Matutino,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048,ZACATECAS,ZSIMB002435,CENTRO DE SALUD LA PINTA,True,2.0,2.0,1,1,0,0,...,1,1,1,0,0,0,0,1,Vespertino,0
1049,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,True,6.0,1.0,1,1,1,1,...,1,1,1,0,0,1,0,1,Vespertino,0
1050,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,True,6.0,2.0,1,1,1,1,...,1,1,1,0,0,1,0,1,Vespertino,0
1051,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,True,6.0,3.0,1,1,1,1,...,1,1,1,0,0,1,0,1,Vespertino,0
1052,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,True,6.0,4.0,1,1,1,1,...,1,1,1,0,0,1,0,1,Vespertino,0

In [17]:
columnas_preguntas = resultado.columns.difference([
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
    "turno_consultorio",
])

resultado[columnas_preguntas] = (
    resultado[columnas_preguntas]
    .apply(pd.to_numeric, errors="coerce")
    .fillna(0)
)

In [18]:
# Columnas que son preguntas
columnas_preguntas = resultado.columns.difference([
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
])

resumen = (
    resultado
    .groupby("clues_imb", as_index=False)
    .agg(
        entidad=("entidad", "first"),
        nombre_de_la_unidad=("nombre_de_la_unidad", "first"),
        internet=("internet", "first"),
        consultorios_habilitados=("consultorios_habilitados", "max"),
        consultorio=("consultorio", "max"),   # Número de consultorios
        **{col: (col, "sum") for col in columnas_preguntas}
    )
)

In [19]:
resumen

,clues_imb,entidad,nombre_de_la_unidad,internet,consultorios_habilitados,consultorio,banco_de_altura_consultorio,banco_giratorio_consultorio,bascula_electronica__con_estadimetro_consultorio,bascula_pesabebes_electronica_consultorio,...,silla_para_el_acompanante_consultorio,silla_para_el_paciente_consultorio,sillon_giratorio_de_respaldo_bajo_consultorio,termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio,termometro_de_vastago_consultorio,termometro_digital_consultorio,tijera_recta_consultorio,torundera_con_tapa_de_acero_inoxidable_consultorio,turno_consultorio,vaso_contenedor__de_vacunas_consultorio
0,BCIMB000092,BAJA CALIFORNIA,FRACCIONAMIENTO MAR,False,NaN,3.0,2.0,1.0,1.0,0.0,...,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,MatutinoMatutinoMatutino,0.0
1,BCIMB000302,BAJA CALIFORNIA,HÉROES DE LA INDEPENDENCIA,True,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,Matutino,0.0
2,BCIMB000314,BAJA CALIFORNIA,VALLE DE LA TRINIDAD,True,2.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,Matutino,0.0
3,BCIMB000536,BAJA CALIFORNIA,DURANGO,True,1.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,Matutino,1.0
4,BCIMB000990,BAJA CALIFORNIA,PEDREGAL DE SANTA JULIA,True,NaN,1.0,2.0,0.0,1.0,2.0,...,2.0,2.0,2.0,4.0,5.0,0.0,1.0,0.0,Matutino,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,ZSIMB001641,ZACATECAS,CENTRO DE SALUD ZACATECAS,None,12.0,6.0,6.0,5.0,6.0,3.0,...,6.0,6.0,6.0,0.0,0.0,6.0,0.0,6.0,VespertinoVespertinoAmbosAmbos,0.0
581,ZSIMB001822,ZACATECAS,CENTRO DE SALUD COL. EMILIANO ZAPATA,True,2.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,Vespertino,0.0
582,ZSIMB002102,ZACATECAS,CENTRO DE SALUD MARTÍNEZ DOMÍNGUEZ,True,2.0,1.0,1.0,0.0,0.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,Vespertino,0.0
583,ZSIMB002435,ZACATECAS,CENTRO DE SALUD LA PINTA,True,2.0,2.0,2.0,2.0,0.0,0.0,...,2.0,2.0,2.0,0.0,0.0,0.0,0.0,2.0,VespertinoVespertino,0.0
584,ZSIMB002522,ZACATECAS,CENTRO DE SALUD FRESNILLO 2,True,6.0,4.0,4.0,4.0,4.0,4.0,...,4.0,4.0,4.0,0.0,0.0,4.0,0.0,4.0,VespertinoVespertinoVespertinoVespertino,0.0

In [20]:
# resultado.loc[
#     resultado["clues_imb"] == "CCIMB000954",
#     [
#         "consultorio",
#        'turno_consultorio'
#     ]
# ]

In [21]:
resultado.loc[
    resultado["clues_imb"] == "CCIMB000930",
    "banco_de_altura_consultorio"
].apply(type)

24    <class 'float'>
25    <class 'float'>
26    <class 'float'>
27    <class 'float'>
28    <class 'float'>
29    <class 'float'>
Name: banco_de_altura_consultorio, dtype: object

In [22]:
# Normalizar internet a 0/1 sin warnings de replace
resumen["internet"] = (
    resumen["internet"]
    .astype(str)
    .str.strip()
    .str.lower()
    .map({
        "true": 1,
        "false": 0,
        "1": 1,
        "0": 0,
        "si": 1,
        "no": 0,
    })
    .fillna(0)
    .astype(int)
)

# Columnas que NO se deben sumar
columnas_excluir = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "turno_consultorio",
]

# Seleccionar columnas a sumar y forzarlas a numerico
columnas_sumar = [c for c in resumen.columns if c not in columnas_excluir]
resumen[columnas_sumar] = (
    resumen[columnas_sumar]
    .apply(pd.to_numeric, errors="coerce")
    .fillna(0)
)

# Agrupar por entidad
resumen_entidad = (
    resumen
    .groupby("entidad", as_index=False)[columnas_sumar]
    .sum()
)

# Mostrar resultado
print(resumen_entidad.head())

               entidad  internet  consultorios_habilitados  consultorio  \
0      BAJA CALIFORNIA         5                       4.0          8.0
1  BAJA CALIFORNIA SUR         2                       2.0          4.0
2             CAMPECHE        14                      23.0         21.0
3              CHIAPAS        12                      36.0         39.0
4             GUERRERO        65                     107.0        121.0

   banco_de_altura_consultorio  banco_giratorio_consultorio  \
0                          7.0                          4.0
1                          2.0                          0.0
2                         12.0                         15.0
3                         31.0                         23.0
4                         95.0                         84.0

   bascula_electronica__con_estadimetro_consultorio  \
0                                               4.0
1                                               0.0
2                                               5.0
3                                              15.0
4                                              48.0

   bascula_pesabebes_electronica_consultorio  \
0                                        3.0
1                                        0.0
2                                        4.0
3                                       11.0
4                                       78.0

   bote_sanitario_con_pedal_consultorio  \
0                                   9.0
1                                   0.0
2                                  15.0
3                                  17.0
4                                  57.0

   caja_portalaminilla_de_plastico_con_separadores_consultorio  ...  \
0                                                1.0            ...
1                                                0.0            ...
2                                                1.0            ...
3                                                4.0            ...
4                                               19.0            ...

   porta_rollo_para_papel_kraft_o_sabanas_consultorio  \
0                                                3.0
1                                                0.0
2                                                0.0
3                                               17.0
4                                               13.0

   silla_para_el_acompanante_consultorio  silla_para_el_paciente_consultorio  \
0                                    7.0                                 7.0
1                                    0.0                                 0.0
2                                   16.0                                16.0
3                                   34.0                                41.0
4                                  132.0                               168.0

   sillon_giratorio_de_respaldo_bajo_consultorio  \
0                                            6.0
1                                            0.0
2                                            4.0
3                                           31.0
4                                           90.0

   termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio  \
0                                                5.0
1                                                0.0
2                                                6.0
3                                               49.0
4                                              106.0

   termometro_de_vastago_consultorio  termometro_digital_consultorio  \
0                                6.0                             1.0
1                                0.0                             0.0
2                                4.0                            17.0
3                               21.0                            34.0
4                               65.0                            95.0

   tijera_recta_consultorio  \
0                       3.0
1                       0.0
2                       5.0
3                       9.0
4                      83.0

   torundera_con_tapa_de_acero_inoxidable_consultorio  \
0                                                3.0
1                                                0.0
2                                               16.0
3                                               24.0
4                                              114.0

   vaso_contenedor__de_vacunas_consultorio
0                                      3.0
1                                      0.0
2                                      3.0
3                                     24.0
4                                     72.0

[5 rows x 48 columns]

In [23]:
# Convertir internet a 0/1
resumen["internet"] = (
    resumen["internet"]
    .replace({
        True: 1,
        False: 0,
        "True": 1,
        "False": 0
    })
    .fillna(0)
    .astype(int)
)

# Columnas que NO se deben sumar
columnas_excluir = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "turno_consultorio",
]

# Columnas a sumar
columnas_sumar = resumen.columns.difference(columnas_excluir)

# Agrupar por entidad
resumen_entidad = (
    resumen
    .groupby("entidad", as_index=False)[columnas_sumar]
    .sum()
)

In [24]:
resumen_entidad

,entidad,banco_de_altura_consultorio,banco_giratorio_consultorio,bascula_electronica__con_estadimetro_consultorio,bascula_pesabebes_electronica_consultorio,bote_sanitario_con_pedal_consultorio,caja_portalaminilla_de_plastico_con_separadores_consultorio,carta_snellen_con_marco_consultorio,charola_de_mayo_de_acero_inoxidable_consultorio,cinta_metrica_consultorio,...,porta_rollo_para_papel_kraft_o_sabanas_consultorio,silla_para_el_acompanante_consultorio,silla_para_el_paciente_consultorio,sillon_giratorio_de_respaldo_bajo_consultorio,termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio,termometro_de_vastago_consultorio,termometro_digital_consultorio,tijera_recta_consultorio,torundera_con_tapa_de_acero_inoxidable_consultorio,vaso_contenedor__de_vacunas_consultorio
0,BAJA CALIFORNIA,7.0,4.0,4.0,3.0,9.0,1.0,2.0,4.0,7.0,...,3.0,7.0,7.0,6.0,5.0,6.0,1.0,3.0,3.0,3.0
1,BAJA CALIFORNIA SUR,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,CAMPECHE,12.0,15.0,5.0,4.0,15.0,1.0,3.0,17.0,14.0,...,0.0,16.0,16.0,4.0,6.0,4.0,17.0,5.0,16.0,3.0
3,CHIAPAS,31.0,23.0,15.0,11.0,17.0,4.0,1.0,29.0,45.0,...,17.0,34.0,41.0,31.0,49.0,21.0,34.0,9.0,24.0,24.0
4,GUERRERO,95.0,84.0,48.0,78.0,57.0,19.0,20.0,79.0,117.0,...,13.0,132.0,168.0,90.0,106.0,65.0,95.0,83.0,114.0,72.0
5,HIDALGO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,MEXICO,380.0,326.0,104.0,187.0,253.0,23.0,29.0,138.0,222.0,...,60.0,435.0,449.0,232.0,187.0,311.0,171.0,93.0,210.0,294.0
7,MICHOACAN DE OCAMPO,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,NAYARIT,31.0,33.0,12.0,21.0,12.0,7.0,8.0,25.0,36.0,...,10.0,49.0,61.0,28.0,52.0,30.0,35.0,29.0,48.0,31.0
9,OAXACA,24.0,18.0,9.0,7.0,15.0,5.0,10.0,19.0,20.0,...,4.0,31.0,37.0,21.0,10.0,11.0,20.0,16.0,24.0,9.0
10,QUINTANA ROO,85.0,76.0,46.0,50.0,23.0,7.0,12.0,57.0,84.0,...,20.0,104.0,156.0,56.0,67.0,39.0,77.0,52.0,97.0,46.0
11,SAN LUIS POTOSI,46.0,44.0,20.0,15.0,39.0,1.0,5.0,37.0,37.0,...,15.0,49.0,55.0,44.0,15.0,15.0,25.0,28.0,36.0,18.0
12,SINALOA,36.0,37.0,35.0,28.0,58.0,42.0,83.0,30.0,64.0,...,39.0,69.0,72.0,61.0,46.0,45.0,80.0,65.0,80.0,47.0
13,TAMAULIPAS,73.0,54.0,19.0,22.0,40.0,9.0,18.0,54.0,63.0,...,17.0,78.0,86.0,39.0,78.0,65.0,52.0,56.0,63.0,52.0
14,VERACRUZ DE IGNACIO DE LA LLAVE,78.0,68.0,29.0,14.0,42.0,15.0,10.0,49.0,88.0,...,44.0,113.0,129.0,81.0,40.0,58.0,53.0,43.0,46.0,38.0
15,ZACATECAS,35.0,22.0,18.0,9.0,30.0,1.0,12.0,23.0,35.0,...,77.0,38.0,38.0,37.0,0.0,0.0,20.0,6.0,20.0,0.0

In [ ]:
import json
from pathlib import Path

base_clues = (
    base[["clues_imb"]]
    .dropna()
    .drop_duplicates()
    .assign(clues_imb=lambda df: df["clues_imb"].astype(str).str.strip())
)
base_clues = base_clues[base_clues["clues_imb"] != ""]

output_dir = Path.cwd() / "public"
output_dir.mkdir(parents=True, exist_ok=True)

clues_path = output_dir / "base_clues.json"
clues_path.write_text(
    json.dumps(base_clues.to_dict(orient="records"), ensure_ascii=False, indent=2),
    encoding="utf-8",
)

base_clues_total = (
    base["clues_imb"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_clues_total = base_clues_total[base_clues_total != ""]

base_entidades_esperadas = (
    base["entidad"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_entidades_esperadas = base_entidades_esperadas[base_entidades_esperadas != ""].nunique()

meta_payload = {
    "clues_total": int(len(base_clues_total)),
    "clues_unicas": int(base_clues["clues_imb"].nunique()),
    "entidades_esperadas": int(base_entidades_esperadas),
}

meta_path = output_dir / "base_meta.json"
meta_path.write_text(
    json.dumps(meta_payload, ensure_ascii=False, indent=2),
    encoding="utf-8",
)

print(f"Archivo generado: {clues_path}")
print(f"Archivo generado: {meta_path}")
print(f"CLUES total base: {meta_payload['clues_total']}")
print(f"CLUES unicas base: {meta_payload['clues_unicas']}")
print(f"Entidades esperadas: {meta_payload['entidades_esperadas']}")

Archivo generado: c:\Users\Tesla\Downloads\reporte_angeles\reporte-_angeles\public\base_clues.json
CLUES esperadas: 636

In [27]:
base_clues_total = (
    base["clues_imb"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_clues_total = base_clues_total[base_clues_total != ""]

base_clues_unicas = base_clues_total.nunique()
base_clues_filas = len(base_clues_total)
base_entidades_esperadas = (
    base["entidad"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_entidades_esperadas = base_entidades_esperadas[base_entidades_esperadas != ""].nunique()

print("clues filas base:", base_clues_filas)
print("clues unicas base:", base_clues_unicas)
print("entidades esperadas base:", base_entidades_esperadas)

clues filas base: 1272
clues unicas base: 636
entidades esperadas base: 20