In [68]:
import pandas as pd
import os
usuario = os.getlogin()

In [69]:
import pandas as pd

sheet_id = "1maRNGDuU9rEFWZLgMdhJS1waAnJxl6ENntm-nyD0tq8"
gid = "1765182479"

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}"

base_an = pd.read_csv(url)

In [70]:
base = pd.read_excel(fr"C:\Users\{usuario}\Downloads\nuevo-f\formulario-ang\bases\UnidadesIMB_CS!_v2.xlsx",sheet_name="Sheet 1")
clues = pd.read_parquet(fr"C:\Users\{usuario}\IMSS-BIENESTAR\División de Procesamiento de información - Repositorio de Datos\CLUES\clues.parquet")

In [71]:
base_an = base_an.drop(columns=["nombre_de_la_unidad"])

In [72]:
base_an

,fecha_registro,tipo_registro,entidad,usuario_nombre,usuario_email,clues_imb,categoria_gerencial_ampliada,internet,consultorios_habilitados,consultorio,pregunta,valor,turno
0,15/07/2026 20:33:13,unidad,CAMPECHE,Jesús Antonio Santini Pérez,drsantiniperez@gmail.com,CCIMB000085,NaN,True,7.0,NaN,internet,NaN,NaN
1,17/07/2026 11:28:26,unidad,HIDALGO,Armando Hernandez Libreros,armando.hernandez@imssbienestar.gob.mx,HGIMB000530,NaN,True,2.0,NaN,internet,NaN,NaN
2,9/07/2026 15:34:57,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,1.0,equipo_de_computo_consultorio_1,1,NaN
3,8/07/2026 12:52:10,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,2.0,equipo_de_computo_consultorio_2,1,NaN
4,8/07/2026 12:52:20,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,1.0,banco_de_altura_consultorio_1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47372,20/07/2026 13:01:15,respuesta,OAXACA,FAVIO CORTES JOAQUIN,cs2nbhuayapam2025@gmail.com,OCIMB001226,NaN,NaN,NaN,1.0,mesa_de_mayo_de_acero_inoxidable_consultorio_1,0,NaN
47373,20/07/2026 13:01:50,respuesta,OAXACA,FAVIO CORTES JOAQUIN,cs2nbhuayapam2025@gmail.com,OCIMB001226,NaN,NaN,NaN,1.0,mesa_pasteur_consultorio_1,0,NaN
47374,20/07/2026 13:02:17,respuesta,OAXACA,FAVIO CORTES JOAQUIN,cs2nbhuayapam2025@gmail.com,OCIMB001226,NaN,NaN,NaN,1.0,mesa_universal_para_exploracion_consultorio_1,1,NaN
47375,20/07/2026 13:02:22,unidad,GUERRERO,José Angel Ocampo Castro,c.s.sanagustinoapan.@gmail.com,GRIMB006860,NaN,True,NaN,NaN,internet,NaN,NaN
47376,20/07/2026 13:02:30,unidad,GUERRERO,José Angel Ocampo Castro,c.s.sanagustinoapan.@gmail.com,GRIMB006860,NaN,NaN,1.0,NaN,consultorios_habilitados,NaN,NaN

In [73]:
base_an.columns.tolist()

['fecha_registro',
 'tipo_registro',
 'entidad',
 'usuario_nombre',
 'usuario_email',
 'clues_imb',
 'categoria_gerencial_ampliada',
 'internet',
 'consultorios_habilitados',
 'consultorio',
 'pregunta',
 'valor',
 'turno']

In [74]:
col = ["clues_imb"]
base = base[col]

In [75]:
base

        clues_imb
0     BCIMB000051
1     BCIMB000092
2     BCIMB000162
3     BCIMB000186
4     BCIMB000191
...           ...
2822  GRIMB010244
2823  GRIMB010256
2824  GRIMB010565
2825  SRIMB001071
2826  TCIMB000704

[2827 rows x 1 columns]

In [76]:
base = base.merge(
    clues[["clues_imb", "entidad",'nombre_de_la_unidad']],
    on="clues_imb",
    how="left"
)

In [77]:
base_an = base_an.merge(
    clues[["clues_imb",'nombre_de_la_unidad']],
    on="clues_imb",
    how="left"
)

In [78]:
b = pd.read_excel(fr"C:\Users\{usuario}\Downloads\nuevo-f\formulario-ang\bases\UM_IMB_SUS.xlsx",sheet_name="Hoja2")

In [79]:
b = b.drop(index=[3])
b = b.drop(columns=['Unnamed: 1'])
b = b.rename(columns={
   'CLUES' : 'preguntas',
})

In [80]:
base_an

,fecha_registro,tipo_registro,entidad,usuario_nombre,usuario_email,clues_imb,categoria_gerencial_ampliada,internet,consultorios_habilitados,consultorio,pregunta,valor,turno,nombre_de_la_unidad
0,15/07/2026 20:33:13,unidad,CAMPECHE,Jesús Antonio Santini Pérez,drsantiniperez@gmail.com,CCIMB000085,NaN,True,7.0,NaN,internet,NaN,NaN,CENTRO DE SALUD DR. WILBERTH ESCALANTE
1,17/07/2026 11:28:26,unidad,HIDALGO,Armando Hernandez Libreros,armando.hernandez@imssbienestar.gob.mx,HGIMB000530,NaN,True,2.0,NaN,internet,NaN,NaN,PROGRESO EL DE ATOTONILCO DE TULA
2,9/07/2026 15:34:57,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,1.0,equipo_de_computo_consultorio_1,1,NaN,FRACCIONAMIENTO MAR
3,8/07/2026 12:52:10,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,2.0,equipo_de_computo_consultorio_2,1,NaN,FRACCIONAMIENTO MAR
4,8/07/2026 12:52:20,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,1.0,banco_de_altura_consultorio_1,1,NaN,FRACCIONAMIENTO MAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47372,20/07/2026 13:01:15,respuesta,OAXACA,FAVIO CORTES JOAQUIN,cs2nbhuayapam2025@gmail.com,OCIMB001226,NaN,NaN,NaN,1.0,mesa_de_mayo_de_acero_inoxidable_consultorio_1,0,NaN,SAN ANDRÉS HUAYAPAM
47373,20/07/2026 13:01:50,respuesta,OAXACA,FAVIO CORTES JOAQUIN,cs2nbhuayapam2025@gmail.com,OCIMB001226,NaN,NaN,NaN,1.0,mesa_pasteur_consultorio_1,0,NaN,SAN ANDRÉS HUAYAPAM
47374,20/07/2026 13:02:17,respuesta,OAXACA,FAVIO CORTES JOAQUIN,cs2nbhuayapam2025@gmail.com,OCIMB001226,NaN,NaN,NaN,1.0,mesa_universal_para_exploracion_consultorio_1,1,NaN,SAN ANDRÉS HUAYAPAM
47375,20/07/2026 13:02:22,unidad,GUERRERO,José Angel Ocampo Castro,c.s.sanagustinoapan.@gmail.com,GRIMB006860,NaN,True,NaN,NaN,internet,NaN,NaN,R-01 SAN AGUSTÍN OAPAN
47376,20/07/2026 13:02:30,unidad,GUERRERO,José Angel Ocampo Castro,c.s.sanagustinoapan.@gmail.com,GRIMB006860,NaN,NaN,1.0,NaN,consultorios_habilitados,NaN,NaN,R-01 SAN AGUSTÍN OAPAN

In [81]:
b

                                            preguntas
0                                 Nombre de la Unidad
1                  Consultorios generales habilitados
2                  Consultorios generales disponibles
4                                   Equipo de cómputo
5                                            Internet
6                                     Banco de altura
7                                     Banco giratorio
8                Báscula electrónica  con estadímetro
9                      Báscula pesabebés electrónica
10                Mesa para colocar báscula pesabebés
11                           Bote sanitario con pedal
12    Caja portalaminilla de plástico con separadores
13                            Carta Snellen con marco
14                Charola de Mayo de acero inoxidable
15                                      Cinta métrica
16                        Contenedor de jabón líquido
17                  Contenedor de toallas desechables
18                        Contenedor rígido para RPBI
19                 Cubeta de acero inoxidable y bolsa
20                                  Escritorio médico
21                                  Esfigmomanómetro
22                                    Espejo vestidor
23                                 Espejos vaginales
24                             Estadímetro pediátrico
25                         Estetoscopio cápsula doble
26       Estetoscopio Pinard o doppler fetal portátil
27  Guarda de medicamentos, materiales o instrumental
28                           Guardarropa con perchero
29             Lámpara de examinación  de pie rodable
30                                            Lavabo
31                                  Martillo percusor
32                   Mesa de Mayo de acero inoxidable
33                                       Mesa Pasteur
34                    Mesa universal para Exploración
35                                          Otoscopio
36                                 Oximetro de pulso
37        Porta cubeta rodable con protector de hule
38             Porta rollo para papel Kraft o sábanas
39                             Silla para el paciente
40                          Silla para el acompañante
41                  Sillón giratorio de respaldo bajo
42  Termo congelante integrado para transporte y c...
43                  Paquetes refrigerantes para termo
44                              Termómetro de vástago
45                                Termómetro digital
46                                       Tijera recta
47             Torundera con tapa de acero Inoxidable
48                        Vaso contenedor  de vacunas

## porcentaje

In [108]:
# TABLA 2 - COMPLETITUD POR UNIDAD

# Número de preguntas del formulario
n_preguntas = len(b)

# Número de consultorios por unidad
consultorios = (
    base_an
    .groupby(["clues_imb","entidad",'nombre_de_la_unidad'],as_index=False)
    ["consultorio"]
    .max()
)

consultorios.rename(
    columns={"consultorio":"consultorios"},
    inplace=True
)

# Preguntas respondidas
respondidas = (
    base_an
    .groupby(["clues_imb","entidad",'nombre_de_la_unidad'])
    .size()
    .reset_index(name="respondidas")
)

tabla_unidades = consultorios.merge(
    respondidas,
    on=["clues_imb","entidad",'nombre_de_la_unidad']
)

tabla_unidades["esperadas"] = (
    tabla_unidades["consultorios"]
    * n_preguntas
)

tabla_unidades["porcentaje"] = (
    tabla_unidades["respondidas"]
    / tabla_unidades["esperadas"]
    *100
).round(1).clip(upper=100)

tabla_unidades = (
    tabla_unidades
    .rename(columns={"clues_imb":"clues"})
    .sort_values("porcentaje")
)

In [83]:
tabla_unidades = tabla_unidades[tabla_unidades["porcentaje"] >= 90]

In [84]:
tabla_unidades.head()

,clues,entidad,nombre_de_la_unidad,consultorios,respondidas,esperadas,porcentaje
311,MCIMB004064,MEXICO,LOS PIRULES,8.0,346,384.0,90.1
268,MCIMB002034,MEXICO,MIGUEL HIDALGO,2.0,87,96.0,90.6
299,MCIMB003900,MEXICO,ESTADO DE MÉXICO NEZAHUALCOYOTL,5.0,219,240.0,91.2
315,MCIMB004110,MEXICO,INDEPENDENCIA,8.0,352,384.0,91.7
351,MCIMB006806,MEXICO,MAYALTEPEC,2.0,88,96.0,91.7

## por unidades

In [85]:
import pandas as pd

# Información de la unidad
unidad = (
    base_an[base_an["tipo_registro"] == "unidad"][
        [
            "entidad",
            "clues_imb",
            "nombre_de_la_unidad",
            "internet",
            "consultorios_habilitados",
        ]
    ]
    .drop_duplicates("clues_imb")
)

# Información por consultorio
respuesta = base_an[base_an["tipo_registro"] == "respuesta"].copy()

# Quitar el sufijo _1, _2, _3...
respuesta["pregunta"] = respuesta["pregunta"].str.replace(
    r"_\d+$", "", regex=True
)

# Convertir preguntas en columnas
pivot = respuesta.pivot_table(
    index=["entidad", "clues_imb", "consultorio"],
    columns="pregunta",
    values="valor",
    aggfunc="first"
).reset_index()

pivot.columns.name = None

# Unir con la información de la unidad
resultado = pivot.merge(
    unidad,
    on=["entidad", "clues_imb"],
    how="left"
)

# Reordenar columnas
columnas_fijas = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
]

columnas_preguntas = [
    c for c in resultado.columns if c not in columnas_fijas
]

resultado = resultado[columnas_fijas + sorted(columnas_preguntas)]

In [86]:
# Filtrar resultado: solo CLUES con >= 90% de respuestas (tabla_unidades)
clues_filtradas = set(tabla_unidades["clues"])
resultado = resultado[resultado["clues_imb"].isin(clues_filtradas)].reset_index(drop=True)
print(f"Filas tras filtro (>=90%): {len(resultado)}  |  CLUES únicas: {resultado['clues_imb'].nunique()}")

Filas tras filtro (>=90%): 829  |  CLUES únicas: 506

In [100]:
clues.columns

Index(['clues_imb', 'clues_ssa_y_sme', 'categoria_gerencial_uas',
       'categoria_gerencial', 'categoria_gerencial_ampliada',
       'clave_de_la_entidad', 'entidad', 'clave_del_municipio', 'municipio',
       'localidad', 'clave_de_la_localidad', 'nombre_de_la_unidad',
       'nombre_comercial', 'estatus_de_operacion', 'nivel_atencion',
       'clave_de_tipologia', 'nombre_de_tipologia', 'clave_de_subtipologia',
       'nombre_de_subtipologia', 'estrato_unidad', 'cve_ro', 'nombre_region',
       'latitud', 'longitud', 'organ_ro', 'tipo_hbc'],
      dtype='object')

In [101]:
resultado = resultado.merge(
    clues[["entidad", "clues_imb", "latitud", "longitud"]],
    on=["entidad", "clues_imb"],
    how="left"
)

In [105]:
resultado.columns

Index(['entidad', 'clues_imb', 'nombre_de_la_unidad', 'internet',
       'consultorios_habilitados', 'consultorio',
       'banco_de_altura_consultorio', 'banco_giratorio_consultorio',
       'bascula_electronica__con_estadimetro_consultorio',
       'bascula_pesabebes_electronica_consultorio',
       'bote_sanitario_con_pedal_consultorio',
       'caja_portalaminilla_de_plastico_con_separadores_consultorio',
       'carta_snellen_con_marco_consultorio',
       'charola_de_mayo_de_acero_inoxidable_consultorio',
       'cinta_metrica_consultorio', 'contenedor_de_jabon_liquido_consultorio',
       'contenedor_de_toallas_desechables_consultorio',
       'contenedor_rigido_para_rpbi_consultorio',
       'cubeta_de_acero_inoxidable_y_bolsa_consultorio',
       'equipo_de_computo_consultorio', 'escritorio_medico_consultorio',
       'esfigmomanometro_consultorio', 'espejo_vestidor_consultorio',
       'espejos_vaginales_consultorio', 'estadimetro_pediatrico_consultorio',
       'estetoscopio_capsula_doble_consultorio',
       'estetoscopio_pinard_o_doppler_fetal_portatil_consultorio',
       'guarda_de_medicamentos,_materiales_o_instrumental_consultorio',
       'guardarropa_con_perchero_consultorio',
       'lampara_de_examinacion__de_pie_rodable_consultorio',
       'lavabo_consultorio', 'martillo_percusor_consultorio',
       'mesa_de_mayo_de_acero_inoxidable_consultorio',
       'mesa_para_colocar_bascula_pesabebes_consultorio',
       'mesa_pasteur_consultorio',
       'mesa_universal_para_exploracion_consultorio', 'otoscopio_consultorio',
       'oximetro_de_pulso_consultorio',
       'paquetes_refrigerantes_para_termo_consultorio',
       'porta_cubeta_rodable_con_protector_de_hule_consultorio',
       'porta_rollo_para_papel_kraft_o_sabanas_consultorio',
       'silla_para_el_acompanante_consultorio',
       'silla_para_el_paciente_consultorio',
       'sillon_giratorio_de_respaldo_bajo_consultorio',
       'termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio',
       'termometro_de_vastago_consultorio', 'termometro_digital_consultorio',
       'tijera_recta_consultorio',
       'torundera_con_tapa_de_acero_inoxidable_consultorio',
       'turno_consultorio', 'vaso_contenedor__de_vacunas_consultorio',
       'latitud', 'longitud'],
      dtype='object')

In [88]:
columnas_preguntas = resultado.columns.difference([
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
    "turno_consultorio",
])

resultado[columnas_preguntas] = (
    resultado[columnas_preguntas]
    .apply(pd.to_numeric, errors="coerce")
    .fillna(0)
)

In [89]:
# Columnas que son preguntas
columnas_preguntas = resultado.columns.difference([
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
])

resumen = (
    resultado
    .groupby("clues_imb", as_index=False)
    .agg(
        entidad=("entidad", "first"),
        nombre_de_la_unidad=("nombre_de_la_unidad", "first"),
        internet=("internet", "first"),
        consultorios_habilitados=("consultorios_habilitados", "max"),
        consultorio=("consultorio", "max"),   # Número de consultorios
        **{col: (col, "sum") for col in columnas_preguntas}
    )
)

In [103]:
resumen = resumen.merge(
    clues[["entidad", "clues_imb", "latitud", "longitud"]],
    on=["entidad", "clues_imb"],
    how="left"
)

In [104]:
resumen

,clues_imb,entidad,nombre_de_la_unidad,internet,consultorios_habilitados,consultorio,banco_de_altura_consultorio,banco_giratorio_consultorio,bascula_electronica__con_estadimetro_consultorio,bascula_pesabebes_electronica_consultorio,...,sillon_giratorio_de_respaldo_bajo_consultorio,termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio,termometro_de_vastago_consultorio,termometro_digital_consultorio,tijera_recta_consultorio,torundera_con_tapa_de_acero_inoxidable_consultorio,turno_consultorio,vaso_contenedor__de_vacunas_consultorio,latitud,longitud
0,BCIMB000302,BAJA CALIFORNIA,HÉROES DE LA INDEPENDENCIA,1,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,Matutino,0.0,31.610915,-115.890043
1,BCIMB000314,BAJA CALIFORNIA,VALLE DE LA TRINIDAD,1,2.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,Matutino,0.0,31.402612,-115.737995
2,BCIMB000536,BAJA CALIFORNIA,DURANGO,1,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,Matutino,1.0,32.249817,-115.256147
3,BCIMB000990,BAJA CALIFORNIA,PEDREGAL DE SANTA JULIA,1,0.0,1.0,2.0,0.0,1.0,2.0,...,2.0,4.0,5.0,0.0,1.0,0.0,Matutino,2.0,32.487771,-117.059844
4,CCIMB000184,CAMPECHE,CENTRO DE SALUD PUERTO RICO,1,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,1.0,1.0,1.0,Vespertino,0.0,18.620689,-91.939520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,ZSIMB001641,ZACATECAS,CENTRO DE SALUD ZACATECAS,0,12.0,6.0,6.0,5.0,6.0,3.0,...,6.0,0.0,0.0,6.0,0.0,6.0,VespertinoVespertinoAmbosAmbos,0.0,22.773375,-102.597295
502,ZSIMB001822,ZACATECAS,CENTRO DE SALUD COL. EMILIANO ZAPATA,1,2.0,1.0,1.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,Vespertino,0.0,23.191013,-102.866952
503,ZSIMB002102,ZACATECAS,CENTRO DE SALUD MARTÍNEZ DOMÍNGUEZ,1,2.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,Vespertino,0.0,22.749695,-102.478009
504,ZSIMB002435,ZACATECAS,CENTRO DE SALUD LA PINTA,1,2.0,2.0,2.0,2.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,2.0,VespertinoVespertino,0.0,22.785735,-102.565062
505,ZSIMB002522,ZACATECAS,CENTRO DE SALUD FRESNILLO 2,1,6.0,4.0,4.0,4.0,4.0,4.0,...,4.0,0.0,0.0,4.0,0.0,4.0,VespertinoVespertinoVespertinoVespertino,0.0,23.183786,-102.864666

In [91]:
# resultado.loc[
#     resultado["clues_imb"] == "CCIMB000954",
#     [
#         "consultorio",
#        'turno_consultorio'
#     ]
# ]

In [92]:
resultado.loc[
    resultado["clues_imb"] == "CCIMB000930",
    "banco_de_altura_consultorio"
].apply(type)

Series([], Name: banco_de_altura_consultorio, dtype: float64)

In [93]:
# Normalizar internet a 0/1 sin warnings de replace
resumen["internet"] = (
    resumen["internet"]
    .astype(str)
    .str.strip()
    .str.lower()
    .map({
        "true": 1,
        "false": 0,
        "1": 1,
        "0": 0,
        "si": 1,
        "no": 0,
    })
    .fillna(0)
    .astype(int)
)

# Columnas que NO se deben sumar
columnas_excluir = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "turno_consultorio",
]

# Seleccionar columnas a sumar y forzarlas a numerico
columnas_sumar = [c for c in resumen.columns if c not in columnas_excluir]
resumen[columnas_sumar] = (
    resumen[columnas_sumar]
    .apply(pd.to_numeric, errors="coerce")
    .fillna(0)
)

# Agrupar por entidad
resumen_entidad = (
    resumen
    .groupby("entidad", as_index=False)[columnas_sumar]
    .sum()
)

# Mostrar resultado
print(resumen_entidad.head())

           entidad  internet  consultorios_habilitados  consultorio  \
0  BAJA CALIFORNIA         4                       4.0          4.0
1         CAMPECHE         5                       7.0          5.0
2          CHIAPAS         8                      27.0         23.0
3           COLIMA         1                       1.0          1.0
4         GUERRERO        88                     145.0        161.0

   banco_de_altura_consultorio  banco_giratorio_consultorio  \
0                          4.0                          3.0
1                          4.0                          5.0
2                         24.0                         16.0
3                          2.0                          2.0
4                        136.0                        125.0

   bascula_electronica__con_estadimetro_consultorio  \
0                                               3.0
1                                               1.0
2                                              12.0
3                                               1.0
4                                              71.0

   bascula_pesabebes_electronica_consultorio  \
0                                        3.0
1                                        1.0
2                                        9.0
3                                        1.0
4                                      111.0

   bote_sanitario_con_pedal_consultorio  \
0                                   8.0
1                                   5.0
2                                  11.0
3                                   2.0
4                                  73.0

   caja_portalaminilla_de_plastico_con_separadores_consultorio  ...  \
0                                                1.0            ...
1                                                0.0            ...
2                                                3.0            ...
3                                                0.0            ...
4                                               30.0            ...

   porta_rollo_para_papel_kraft_o_sabanas_consultorio  \
0                                                3.0
1                                                0.0
2                                               11.0
3                                                6.0
4                                               26.0

   silla_para_el_acompanante_consultorio  silla_para_el_paciente_consultorio  \
0                                    5.0                                 5.0
1                                    4.0                                 5.0
2                                   28.0                                35.0
3                                    7.0                                 2.0
4                                  211.0                               251.0

   sillon_giratorio_de_respaldo_bajo_consultorio  \
0                                            4.0
1                                            2.0
2                                           30.0
3                                            0.0
4                                          124.0

   termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio  \
0                                                5.0
1                                                3.0
2                                               43.0
3                                                2.0
4                                              155.0

   termometro_de_vastago_consultorio  termometro_digital_consultorio  \
0                                6.0                             1.0
1                                2.0                             4.0
2                               20.0                            27.0
3                                3.0                             2.0
4                              106.0                           140.0

   tijera_recta_consultorio  \
0                       3.0
1                       2.0
2                       3.0
3                       3.0
4                     128.0

   torundera_con_tapa_de_acero_inoxidable_consultorio  \
0                                                3.0
1                                                4.0
2                                               18.0
3                                                1.0
4                                              178.0

   vaso_contenedor__de_vacunas_consultorio
0                                      3.0
1                                      1.0
2                                     23.0
3                                      1.0
4                                    100.0

[5 rows x 48 columns]

In [94]:
# Convertir internet a 0/1
resumen["internet"] = (
    resumen["internet"]
    .replace({
        True: 1,
        False: 0,
        "True": 1,
        "False": 0
    })
    .fillna(0)
    .astype(int)
)

# Columnas que NO se deben sumar
columnas_excluir = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "turno_consultorio",
]

# Columnas a sumar
columnas_sumar = resumen.columns.difference(columnas_excluir)

# Agrupar por entidad
resumen_entidad = (
    resumen
    .groupby("entidad", as_index=False)[columnas_sumar]
    .sum()
)

In [95]:
resumen_entidad

,entidad,banco_de_altura_consultorio,banco_giratorio_consultorio,bascula_electronica__con_estadimetro_consultorio,bascula_pesabebes_electronica_consultorio,bote_sanitario_con_pedal_consultorio,caja_portalaminilla_de_plastico_con_separadores_consultorio,carta_snellen_con_marco_consultorio,charola_de_mayo_de_acero_inoxidable_consultorio,cinta_metrica_consultorio,...,porta_rollo_para_papel_kraft_o_sabanas_consultorio,silla_para_el_acompanante_consultorio,silla_para_el_paciente_consultorio,sillon_giratorio_de_respaldo_bajo_consultorio,termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio,termometro_de_vastago_consultorio,termometro_digital_consultorio,tijera_recta_consultorio,torundera_con_tapa_de_acero_inoxidable_consultorio,vaso_contenedor__de_vacunas_consultorio
0,BAJA CALIFORNIA,4.0,3.0,3.0,3.0,8.0,1.0,2.0,4,6.0,...,3.0,5.0,5.0,4.0,5.0,6.0,1.0,3.0,3.0,3.0
1,CAMPECHE,4.0,5.0,1.0,1.0,5.0,0.0,2.0,5,4.0,...,0.0,4.0,5.0,2.0,3.0,2.0,4.0,2.0,4.0,1.0
2,CHIAPAS,24.0,16.0,12.0,9.0,11.0,3.0,0.0,16,44.0,...,11.0,28.0,35.0,30.0,43.0,20.0,27.0,3.0,18.0,23.0
3,COLIMA,2.0,2.0,1.0,1.0,2.0,0.0,1.0,1,1.0,...,6.0,7.0,2.0,0.0,2.0,3.0,2.0,3.0,1.0,1.0
4,GUERRERO,136.0,125.0,71.0,111.0,73.0,30.0,22.0,128,170.0,...,26.0,211.0,251.0,124.0,155.0,106.0,140.0,128.0,178.0,100.0
5,MEXICO,284.0,245.0,76.0,114.0,189.0,19.0,27.0,116,197.0,...,53.0,370.0,384.0,197.0,180.0,298.0,139.0,73.0,164.0,288.0
6,NAYARIT,30.0,32.0,12.0,20.0,11.0,7.0,8.0,24,35.0,...,10.0,48.0,60.0,28.0,50.0,29.0,33.0,28.0,45.0,30.0
7,OAXACA,24.0,18.0,9.0,7.0,17.0,4.0,9.0,20,22.0,...,6.0,34.0,40.0,24.0,10.0,11.0,20.0,14.0,26.0,9.0
8,QUINTANA ROO,98.0,83.0,50.0,53.0,25.0,8.0,13.0,61,97.0,...,23.0,118.0,177.0,54.0,70.0,45.0,91.0,59.0,106.0,49.0
9,SAN LUIS POTOSI,38.0,35.0,15.0,12.0,32.0,1.0,4.0,29,26.0,...,11.0,36.0,42.0,36.0,13.0,12.0,23.0,25.0,30.0,14.0
10,SINALOA,7.0,14.0,1.0,0.0,6.0,0.0,0.0,2,6.0,...,0.0,7.0,7.0,6.0,0.0,0.0,4.0,1.0,5.0,0.0
11,TAMAULIPAS,72.0,54.0,18.0,23.0,41.0,9.0,16.0,53,62.0,...,9.0,76.0,84.0,39.0,74.0,62.0,51.0,53.0,61.0,50.0
12,VERACRUZ DE IGNACIO DE LA LLAVE,67.0,60.0,27.0,13.0,41.0,15.0,6.0,45,81.0,...,41.0,112.0,125.0,78.0,41.0,58.0,49.0,39.0,43.0,30.0
13,ZACATECAS,34.0,22.0,18.0,9.0,30.0,1.0,12.0,23,35.0,...,75.0,37.0,37.0,37.0,0.0,0.0,19.0,5.0,19.0,0.0

In [96]:
import json
from pathlib import Path
from datetime import datetime

base_clues = (
    base[["clues_imb"]]
    .dropna()
    .drop_duplicates()
    .assign(clues_imb=lambda df: df["clues_imb"].astype(str).str.strip())
)
base_clues = base_clues[base_clues["clues_imb"] != ""]

output_dir = Path.cwd() / "public"
output_dir.mkdir(parents=True, exist_ok=True)

clues_path = output_dir / "base_clues.json"
clues_path.write_text(
    json.dumps(base_clues.to_dict(orient="records"), ensure_ascii=False, indent=2),
    encoding="utf-8",
)

base_clues_total = (
    base["clues_imb"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_clues_total = base_clues_total[base_clues_total != ""]

base_entidades_esperadas = (
    base["entidad"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_entidades_esperadas = base_entidades_esperadas[base_entidades_esperadas != ""].nunique()

meta_payload = {
    "clues_total": int(len(base_clues_total)),
    "clues_unicas": int(base_clues["clues_imb"].nunique()),
    "entidades_esperadas": int(base_entidades_esperadas),
    "script_last_run_at": datetime.now().isoformat(timespec="seconds"),
}

meta_path = output_dir / "base_meta.json"
meta_path.write_text(
    json.dumps(meta_payload, ensure_ascii=False, indent=2),
    encoding="utf-8",
)

print(f"Archivo generado: {clues_path}")
print(f"Archivo generado: {meta_path}")
print(f"CLUES total base: {meta_payload['clues_total']}")
print(f"CLUES unicas base: {meta_payload['clues_unicas']}")
print(f"Entidades esperadas: {meta_payload['entidades_esperadas']}")
print(f"Script run at: {meta_payload['script_last_run_at']}")

Archivo generado: c:\Users\jose.valdez\Downloads\repor-arm\reporte-_angeles\public\base_clues.json
Archivo generado: c:\Users\jose.valdez\Downloads\repor-arm\reporte-_angeles\public\base_meta.json
CLUES total base: 2827
CLUES unicas base: 2191
Entidades esperadas: 22
Script run at: 2026-07-20T13:02:41

In [97]:
# Exportar CLUES filtradas (>=90%) a public/tabla_unidades.json
tabla_unidades_path = output_dir / "tabla_unidades.json"
clues_para_export = (
    tabla_unidades["clues"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
    .tolist()
)
tabla_unidades_path.write_text(
    json.dumps(clues_para_export, ensure_ascii=False, indent=2),
    encoding="utf-8",
)
print(f"Archivo generado: {tabla_unidades_path}")
print(f"CLUES exportadas (>=90%): {len(clues_para_export)}")

Archivo generado: c:\Users\jose.valdez\Downloads\repor-arm\reporte-_angeles\public\tabla_unidades.json
CLUES exportadas (>=90%): 506

In [107]:
# Exportar puntos geo de CLUES a public/clues_geo.json
geo_cols = ["clues_imb", "nombre_de_la_unidad", "entidad", "latitud", "longitud", "internet", "consultorio"]
available_cols = [c for c in geo_cols if c in resumen.columns]

clues_geo = (
    resumen[available_cols]
    .dropna(subset=["latitud", "longitud"])
    .copy()
)

clues_geo["internet"] = clues_geo["internet"].apply(
    lambda v: str(v).strip().lower() in ("true", "1", "si", "sí", "yes")
)
clues_geo["latitud"] = pd.to_numeric(clues_geo["latitud"], errors="coerce")
clues_geo["longitud"] = pd.to_numeric(clues_geo["longitud"], errors="coerce")
clues_geo = clues_geo.dropna(subset=["latitud", "longitud"])

# Agregar % llenado desde tabla_unidades
tabla_pct = tabla_unidades[["clues", "porcentaje"]].rename(
    columns={"clues": "clues_imb", "porcentaje": "pct_llenado"}
)
clues_geo = clues_geo.merge(tabla_pct, on="clues_imb", how="left")
clues_geo["pct_llenado"] = clues_geo["pct_llenado"].fillna(0).round(1)

clues_geo_path = output_dir / "clues_geo.json"
clues_geo_path.write_text(
    json.dumps(
        clues_geo.rename(columns={"latitud": "lat", "longitud": "lng", "consultorio": "consultorios"})
                 .to_dict(orient="records"),
        ensure_ascii=False,
        indent=2
    ),
    encoding="utf-8",
)
print(f"Archivo generado: {clues_geo_path}")
print(f"Puntos geo exportados: {len(clues_geo)}")

Archivo generado: c:\Users\jose.valdez\Downloads\repor-arm\reporte-_angeles\public\clues_geo.json
Puntos geo exportados: 506

In [98]:
base_clues_total = (
    base["clues_imb"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_clues_total = base_clues_total[base_clues_total != ""]

base_clues_unicas = base_clues_total.nunique()
base_clues_filas = len(base_clues_total)
base_entidades_esperadas = (
    base["entidad"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_entidades_esperadas = base_entidades_esperadas[base_entidades_esperadas != ""].nunique()

print("clues filas base:", base_clues_filas)
print("clues unicas base:", base_clues_unicas)
print("entidades esperadas base:", base_entidades_esperadas)

clues filas base: 2827
clues unicas base: 2191
entidades esperadas base: 22