In [ ]:
import pandas as pd
import os
usuario = os.getlogin()

In [ ]:
import pandas as pd

sheet_id = "1maRNGDuU9rEFWZLgMdhJS1waAnJxl6ENntm-nyD0tq8"
gid = "1765182479"

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}"

base_an = pd.read_csv(url)

In [ ]:
base = pd.read_excel(fr"C:\Users\{usuario}\Downloads\UnidadesIMB_CS!_v2 (1).xlsx",sheet_name="Sheet 1")
clues = pd.read_parquet(fr"C:\Users\{usuario}\IMSS-BIENESTAR\División de Procesamiento de información - Repositorio de Datos\CLUES\clues.parquet")

In [ ]:
base_an = base_an.drop(columns=["nombre_de_la_unidad"])

In [ ]:
base_an

,fecha_registro,tipo_registro,entidad,usuario_nombre,usuario_email,clues_imb,categoria_gerencial_ampliada,internet,consultorios_habilitados,consultorio,pregunta,valor,turno
0,1/07/2026 17:56:29,unidad,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000025,NaN,True,NaN,NaN,internet,NaN,NaN
1,1/07/2026 17:56:39,respuesta,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000025,NaN,NaN,NaN,1.0,turno_consultorio_1,Ambos,NaN
2,9/07/2026 15:35:53,unidad,BAJA CALIFORNIA,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BCIMB000092,NaN,False,NaN,NaN,internet,NaN,NaN
3,3/07/2026 10:26:07,unidad,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000136,NaN,True,NaN,NaN,internet,NaN,NaN
4,3/07/2026 10:28:10,respuesta,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000136,NaN,NaN,NaN,1.0,turno_consultorio_1,Matutino,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38283,17/07/2026 10:15:21,respuesta,GUERRERO,Emmanuel Guzman Carbajal,emmanuelguzca@gmail.com,GRIMB008815,NaN,NaN,NaN,1.0,termometro_digital_consultorio_1,1,NaN
38284,17/07/2026 10:15:24,respuesta,GUERRERO,Emmanuel Guzman Carbajal,emmanuelguzca@gmail.com,GRIMB008815,NaN,NaN,NaN,1.0,tijera_recta_consultorio_1,1,NaN
38285,17/07/2026 10:15:26,respuesta,GUERRERO,Emmanuel Guzman Carbajal,emmanuelguzca@gmail.com,GRIMB008815,NaN,NaN,NaN,1.0,torundera_con_tapa_de_acero_inoxidable_consult...,1,NaN
38286,17/07/2026 10:15:31,respuesta,GUERRERO,Emmanuel Guzman Carbajal,emmanuelguzca@gmail.com,GRIMB008815,NaN,NaN,NaN,1.0,vaso_contenedor__de_vacunas_consultorio_1,1,NaN
38287,17/07/2026 10:15:45,unidad,GUERRERO,YARI GARCÍA CARRILLO,yarigarciac73@gmail.com,GRIMB000176,NaN,True,NaN,NaN,internet,NaN,NaN

In [ ]:
base_an.columns.tolist()

['fecha_registro',
 'tipo_registro',
 'entidad',
 'usuario_nombre',
 'usuario_email',
 'clues_imb',
 'categoria_gerencial_ampliada',
 'internet',
 'consultorios_habilitados',
 'consultorio',
 'pregunta',
 'valor',
 'turno']

In [ ]:
col = ["clues_imb"]
base = base[col]

In [ ]:
base = base.merge(
    clues[["clues_imb", "entidad",'nombre_de_la_unidad']],
    on="clues_imb",
    how="left"
)

In [ ]:
base_an = base_an.merge(
    clues[["clues_imb",'nombre_de_la_unidad']],
    on="clues_imb",
    how="left"
)

In [ ]:
base_an

,fecha_registro,tipo_registro,entidad,usuario_nombre,usuario_email,clues_imb,categoria_gerencial_ampliada,internet,consultorios_habilitados,consultorio,pregunta,valor,turno,nombre_de_la_unidad
0,1/07/2026 17:56:29,unidad,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000025,NaN,True,NaN,NaN,internet,NaN,NaN,CENTRO DE SALUD PUERTO ADOLFO LÓPEZ MATEOS
1,1/07/2026 17:56:39,respuesta,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000025,NaN,NaN,NaN,1.0,turno_consultorio_1,Ambos,NaN,CENTRO DE SALUD PUERTO ADOLFO LÓPEZ MATEOS
2,9/07/2026 15:35:53,unidad,BAJA CALIFORNIA,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BCIMB000092,NaN,False,NaN,NaN,internet,NaN,NaN,FRACCIONAMIENTO MAR
3,3/07/2026 10:26:07,unidad,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000136,NaN,True,NaN,NaN,internet,NaN,NaN,CENTRO DE SALUD BAHÍA TORTUGAS
4,3/07/2026 10:28:10,respuesta,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000136,NaN,NaN,NaN,1.0,turno_consultorio_1,Matutino,NaN,CENTRO DE SALUD BAHÍA TORTUGAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38283,17/07/2026 10:15:21,respuesta,GUERRERO,Emmanuel Guzman Carbajal,emmanuelguzca@gmail.com,GRIMB008815,NaN,NaN,NaN,1.0,termometro_digital_consultorio_1,1,NaN,R-01 LAS PAROTAS
38284,17/07/2026 10:15:24,respuesta,GUERRERO,Emmanuel Guzman Carbajal,emmanuelguzca@gmail.com,GRIMB008815,NaN,NaN,NaN,1.0,tijera_recta_consultorio_1,1,NaN,R-01 LAS PAROTAS
38285,17/07/2026 10:15:26,respuesta,GUERRERO,Emmanuel Guzman Carbajal,emmanuelguzca@gmail.com,GRIMB008815,NaN,NaN,NaN,1.0,torundera_con_tapa_de_acero_inoxidable_consult...,1,NaN,R-01 LAS PAROTAS
38286,17/07/2026 10:15:31,respuesta,GUERRERO,Emmanuel Guzman Carbajal,emmanuelguzca@gmail.com,GRIMB008815,NaN,NaN,NaN,1.0,vaso_contenedor__de_vacunas_consultorio_1,1,NaN,R-01 LAS PAROTAS
38287,17/07/2026 10:15:45,unidad,GUERRERO,YARI GARCÍA CARRILLO,yarigarciac73@gmail.com,GRIMB000176,NaN,True,NaN,NaN,internet,NaN,NaN,U-02 COL. MIGUEL HIDALGO

In [ ]:
b = pd.read_excel(fr"C:\Users\{usuario}\Downloads\UM_IMB_SUS.xlsx",sheet_name="Hoja2")

In [ ]:
b = b.drop(index=[3])
b = b.drop(columns=['Unnamed: 1'])
b = b.rename(columns={
   'CLUES' : 'preguntas',
})

In [ ]:
base_an

,fecha_registro,tipo_registro,entidad,usuario_nombre,usuario_email,clues_imb,categoria_gerencial_ampliada,internet,consultorios_habilitados,consultorio,pregunta,valor,turno,nombre_de_la_unidad
0,1/07/2026 17:56:29,unidad,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000025,NaN,True,NaN,NaN,internet,NaN,NaN,CENTRO DE SALUD PUERTO ADOLFO LÓPEZ MATEOS
1,1/07/2026 17:56:39,respuesta,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000025,NaN,NaN,NaN,1.0,turno_consultorio_1,Ambos,NaN,CENTRO DE SALUD PUERTO ADOLFO LÓPEZ MATEOS
2,9/07/2026 15:35:53,unidad,BAJA CALIFORNIA,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BCIMB000092,NaN,False,NaN,NaN,internet,NaN,NaN,FRACCIONAMIENTO MAR
3,3/07/2026 10:26:07,unidad,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000136,NaN,True,NaN,NaN,internet,NaN,NaN,CENTRO DE SALUD BAHÍA TORTUGAS
4,3/07/2026 10:28:10,respuesta,BAJA CALIFORNIA SUR,Marisol Morales Mirón,marisol.morales@imssbienestar.gob.mx,BSIMB000136,NaN,NaN,NaN,1.0,turno_consultorio_1,Matutino,NaN,CENTRO DE SALUD BAHÍA TORTUGAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38283,17/07/2026 10:15:21,respuesta,GUERRERO,Emmanuel Guzman Carbajal,emmanuelguzca@gmail.com,GRIMB008815,NaN,NaN,NaN,1.0,termometro_digital_consultorio_1,1,NaN,R-01 LAS PAROTAS
38284,17/07/2026 10:15:24,respuesta,GUERRERO,Emmanuel Guzman Carbajal,emmanuelguzca@gmail.com,GRIMB008815,NaN,NaN,NaN,1.0,tijera_recta_consultorio_1,1,NaN,R-01 LAS PAROTAS
38285,17/07/2026 10:15:26,respuesta,GUERRERO,Emmanuel Guzman Carbajal,emmanuelguzca@gmail.com,GRIMB008815,NaN,NaN,NaN,1.0,torundera_con_tapa_de_acero_inoxidable_consult...,1,NaN,R-01 LAS PAROTAS
38286,17/07/2026 10:15:31,respuesta,GUERRERO,Emmanuel Guzman Carbajal,emmanuelguzca@gmail.com,GRIMB008815,NaN,NaN,NaN,1.0,vaso_contenedor__de_vacunas_consultorio_1,1,NaN,R-01 LAS PAROTAS
38287,17/07/2026 10:15:45,unidad,GUERRERO,YARI GARCÍA CARRILLO,yarigarciac73@gmail.com,GRIMB000176,NaN,True,NaN,NaN,internet,NaN,NaN,U-02 COL. MIGUEL HIDALGO

In [ ]:
b

                                            preguntas
0                                 Nombre de la Unidad
1                  Consultorios generales habilitados
2                  Consultorios generales disponibles
4                                   Equipo de cómputo
5                                            Internet
6                                     Banco de altura
7                                     Banco giratorio
8                Báscula electrónica  con estadímetro
9                      Báscula pesabebés electrónica
10                Mesa para colocar báscula pesabebés
11                           Bote sanitario con pedal
12    Caja portalaminilla de plástico con separadores
13                            Carta Snellen con marco
14                Charola de Mayo de acero inoxidable
15                                      Cinta métrica
16                        Contenedor de jabón líquido
17                  Contenedor de toallas desechables
18                        Contenedor rígido para RPBI
19                 Cubeta de acero inoxidable y bolsa
20                                  Escritorio médico
21                                  Esfigmomanómetro
22                                    Espejo vestidor
23                                 Espejos vaginales
24                             Estadímetro pediátrico
25                         Estetoscopio cápsula doble
26       Estetoscopio Pinard o doppler fetal portátil
27  Guarda de medicamentos, materiales o instrumental
28                           Guardarropa con perchero
29             Lámpara de examinación  de pie rodable
30                                            Lavabo
31                                  Martillo percusor
32                   Mesa de Mayo de acero inoxidable
33                                       Mesa Pasteur
34                    Mesa universal para Exploración
35                                          Otoscopio
36                                 Oximetro de pulso
37        Porta cubeta rodable con protector de hule
38             Porta rollo para papel Kraft o sábanas
39                             Silla para el paciente
40                          Silla para el acompañante
41                  Sillón giratorio de respaldo bajo
42  Termo congelante integrado para transporte y c...
43                  Paquetes refrigerantes para termo
44                              Termómetro de vástago
45                                Termómetro digital
46                                       Tijera recta
47             Torundera con tapa de acero Inoxidable
48                        Vaso contenedor  de vacunas

In [ ]:
import pandas as pd

# Información de la unidad
unidad = (
    base_an[base_an["tipo_registro"] == "unidad"][
        [
            "entidad",
            "clues_imb",
            "nombre_de_la_unidad",
            "internet",
            "consultorios_habilitados",
        ]
    ]
    .drop_duplicates("clues_imb")
)

# Información por consultorio
respuesta = base_an[base_an["tipo_registro"] == "respuesta"].copy()

# Quitar el sufijo _1, _2, _3...
respuesta["pregunta"] = respuesta["pregunta"].str.replace(
    r"_\d+$", "", regex=True
)

# Convertir preguntas en columnas
pivot = respuesta.pivot_table(
    index=["entidad", "clues_imb", "consultorio"],
    columns="pregunta",
    values="valor",
    aggfunc="first"
).reset_index()

pivot.columns.name = None

# Unir con la información de la unidad
resultado = pivot.merge(
    unidad,
    on=["entidad", "clues_imb"],
    how="left"
)

# Reordenar columnas
columnas_fijas = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
]

columnas_preguntas = [
    c for c in resultado.columns if c not in columnas_fijas
]

resultado = resultado[columnas_fijas + sorted(columnas_preguntas)]

In [ ]:
resultado

,entidad,clues_imb,nombre_de_la_unidad,internet,consultorios_habilitados,consultorio,banco_de_altura_consultorio,banco_giratorio_consultorio,bascula_electronica__con_estadimetro_consultorio,bascula_pesabebes_electronica_consultorio,...,silla_para_el_acompanante_consultorio,silla_para_el_paciente_consultorio,sillon_giratorio_de_respaldo_bajo_consultorio,termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio,termometro_de_vastago_consultorio,termometro_digital_consultorio,tijera_recta_consultorio,torundera_con_tapa_de_acero_inoxidable_consultorio,turno_consultorio,vaso_contenedor__de_vacunas_consultorio
0,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,False,NaN,1.0,1,0,0,0,...,1,1,1,NaN,NaN,NaN,NaN,NaN,Matutino,NaN
1,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,False,NaN,2.0,1,1,1,0,...,1,1,1,NaN,NaN,NaN,NaN,NaN,Matutino,NaN
2,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,False,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matutino,NaN
3,BAJA CALIFORNIA,BCIMB000302,HÉROES DE LA INDEPENDENCIA,True,1.0,1.0,0,1,0,0,...,1,1,1,0,0,0,1,1,Matutino,0
4,BAJA CALIFORNIA,BCIMB000314,VALLE DE LA TRINIDAD,True,2.0,1.0,1,1,1,1,...,1,1,1,0,0,0,0,1,Matutino,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,ZACATECAS,ZSIMB002435,CENTRO DE SALUD LA PINTA,True,2.0,2.0,1,1,0,0,...,1,1,1,0,0,0,0,1,Vespertino,0
929,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,True,6.0,1.0,1,1,1,1,...,1,1,1,0,0,1,0,1,Vespertino,0
930,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,True,6.0,2.0,1,1,1,1,...,1,1,1,0,0,1,0,1,Vespertino,0
931,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,True,6.0,3.0,1,1,1,1,...,1,1,1,0,0,1,0,1,Vespertino,0
932,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,True,6.0,4.0,1,1,1,1,...,1,1,1,0,0,1,0,1,Vespertino,0

In [ ]:
columnas_preguntas = resultado.columns.difference([
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
    "turno_consultorio",
])

resultado[columnas_preguntas] = (
    resultado[columnas_preguntas]
    .apply(pd.to_numeric, errors="coerce")
    .fillna(0)
)

In [ ]:
# Columnas que son preguntas
columnas_preguntas = resultado.columns.difference([
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
])

resumen = (
    resultado
    .groupby("clues_imb", as_index=False)
    .agg(
        entidad=("entidad", "first"),
        nombre_de_la_unidad=("nombre_de_la_unidad", "first"),
        internet=("internet", "first"),
        consultorios_habilitados=("consultorios_habilitados", "max"),
        consultorio=("consultorio", "max"),   # Número de consultorios
        **{col: (col, "sum") for col in columnas_preguntas}
    )
)

In [ ]:
resumen

,clues_imb,entidad,nombre_de_la_unidad,internet,consultorios_habilitados,consultorio,banco_de_altura_consultorio,banco_giratorio_consultorio,bascula_electronica__con_estadimetro_consultorio,bascula_pesabebes_electronica_consultorio,...,silla_para_el_acompanante_consultorio,silla_para_el_paciente_consultorio,sillon_giratorio_de_respaldo_bajo_consultorio,termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio,termometro_de_vastago_consultorio,termometro_digital_consultorio,tijera_recta_consultorio,torundera_con_tapa_de_acero_inoxidable_consultorio,turno_consultorio,vaso_contenedor__de_vacunas_consultorio
0,BCIMB000092,BAJA CALIFORNIA,FRACCIONAMIENTO MAR,False,NaN,3.0,2.0,1.0,1.0,0.0,...,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,MatutinoMatutinoMatutino,0.0
1,BCIMB000302,BAJA CALIFORNIA,HÉROES DE LA INDEPENDENCIA,True,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,Matutino,0.0
2,BCIMB000314,BAJA CALIFORNIA,VALLE DE LA TRINIDAD,True,2.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,Matutino,0.0
3,BCIMB000536,BAJA CALIFORNIA,DURANGO,True,1.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,Matutino,1.0
4,BCIMB000990,BAJA CALIFORNIA,PEDREGAL DE SANTA JULIA,True,NaN,1.0,2.0,0.0,1.0,2.0,...,2.0,2.0,2.0,4.0,5.0,0.0,1.0,0.0,Matutino,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511,ZSIMB001641,ZACATECAS,CENTRO DE SALUD ZACATECAS,None,12.0,6.0,6.0,5.0,6.0,3.0,...,6.0,6.0,6.0,0.0,0.0,6.0,0.0,6.0,VespertinoVespertinoAmbosAmbos,0.0
512,ZSIMB001822,ZACATECAS,CENTRO DE SALUD COL. EMILIANO ZAPATA,True,2.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,Vespertino,0.0
513,ZSIMB002102,ZACATECAS,CENTRO DE SALUD MARTÍNEZ DOMÍNGUEZ,True,2.0,1.0,1.0,0.0,0.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,Vespertino,0.0
514,ZSIMB002435,ZACATECAS,CENTRO DE SALUD LA PINTA,True,2.0,2.0,2.0,2.0,0.0,0.0,...,2.0,2.0,2.0,0.0,0.0,0.0,0.0,2.0,VespertinoVespertino,0.0
515,ZSIMB002522,ZACATECAS,CENTRO DE SALUD FRESNILLO 2,True,6.0,4.0,4.0,4.0,4.0,4.0,...,4.0,4.0,4.0,0.0,0.0,4.0,0.0,4.0,VespertinoVespertinoVespertinoVespertino,0.0

In [ ]:
# resultado.loc[
#     resultado["clues_imb"] == "CCIMB000954",
#     [
#         "consultorio",
#        'turno_consultorio'
#     ]
# ]

In [ ]:
resultado.loc[
    resultado["clues_imb"] == "CCIMB000930",
    "banco_de_altura_consultorio"
].apply(type)

24    <class 'float'>
25    <class 'float'>
26    <class 'float'>
27    <class 'float'>
28    <class 'float'>
29    <class 'float'>
Name: banco_de_altura_consultorio, dtype: object

In [ ]:
# Convertir la columna internet a 0/1 de forma segura
resumen["internet"] = (
    resumen["internet"]
    .replace({
        True: 1,
        False: 0,
        "True": 1,
        "False": 0,
        "true": 1,
        "false": 0
    })
    .fillna(0)
    .astype(int)
)

# Columnas que NO se deben sumar
columnas_excluir = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
]

# Seleccionar únicamente las columnas a sumar
columnas_sumar = resumen.columns.difference(columnas_excluir)

# Agrupar por entidad
resumen_entidad = (
    resumen
    .groupby("entidad", as_index=False)[columnas_sumar]
    .sum()
)

# Mostrar resultado
print(resumen_entidad.head())

C:\Users\Tesla\AppData\Local\Temp\ipykernel_20952\1752467196.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({

TypeError: can only concatenate str (not "int") to str

In [ ]:
# Convertir internet a 0/1
resumen["internet"] = (
    resumen["internet"]
    .replace({
        True: 1,
        False: 0,
        "True": 1,
        "False": 0
    })
    .fillna(0)
    .astype(int)
)

# Columnas que NO se deben sumar
columnas_excluir = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "turno_consultorio",
]

# Columnas a sumar
columnas_sumar = resumen.columns.difference(columnas_excluir)

# Agrupar por entidad
resumen_entidad = (
    resumen
    .groupby("entidad", as_index=False)[columnas_sumar]
    .sum()
)

In [ ]:
resumen_entidad

,entidad,banco_de_altura_consultorio,banco_giratorio_consultorio,bascula_electronica__con_estadimetro_consultorio,bascula_pesabebes_electronica_consultorio,bote_sanitario_con_pedal_consultorio,caja_portalaminilla_de_plastico_con_separadores_consultorio,carta_snellen_con_marco_consultorio,charola_de_mayo_de_acero_inoxidable_consultorio,cinta_metrica_consultorio,...,porta_rollo_para_papel_kraft_o_sabanas_consultorio,silla_para_el_acompanante_consultorio,silla_para_el_paciente_consultorio,sillon_giratorio_de_respaldo_bajo_consultorio,termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio,termometro_de_vastago_consultorio,termometro_digital_consultorio,tijera_recta_consultorio,torundera_con_tapa_de_acero_inoxidable_consultorio,vaso_contenedor__de_vacunas_consultorio
0,BAJA CALIFORNIA,7.0,4.0,4.0,3.0,9.0,1.0,2.0,4.0,7.0,...,3.0,7.0,7.0,6.0,5.0,6.0,1.0,3.0,3.0,3.0
1,BAJA CALIFORNIA SUR,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,CAMPECHE,12.0,15.0,5.0,4.0,15.0,1.0,3.0,17.0,14.0,...,0.0,16.0,16.0,4.0,6.0,4.0,17.0,5.0,16.0,3.0
3,CHIAPAS,31.0,23.0,15.0,11.0,17.0,4.0,1.0,29.0,45.0,...,17.0,34.0,41.0,31.0,49.0,21.0,34.0,9.0,24.0,24.0
4,GUERRERO,55.0,46.0,25.0,38.0,33.0,9.0,5.0,45.0,56.0,...,4.0,83.0,106.0,42.0,60.0,36.0,46.0,48.0,65.0,35.0
5,MEXICO,341.0,294.0,103.0,169.0,228.0,22.0,22.0,123.0,198.0,...,57.0,387.0,400.0,211.0,167.0,284.0,163.0,86.0,194.0,283.0
6,MICHOACAN DE OCAMPO,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,NAYARIT,31.0,33.0,12.0,21.0,12.0,7.0,8.0,25.0,36.0,...,10.0,49.0,61.0,28.0,52.0,30.0,35.0,29.0,48.0,31.0
8,OAXACA,21.0,16.0,8.0,7.0,13.0,5.0,9.0,16.0,17.0,...,4.0,20.0,25.0,17.0,9.0,8.0,20.0,14.0,19.0,8.0
9,QUINTANA ROO,73.0,67.0,41.0,43.0,20.0,7.0,14.0,52.0,76.0,...,18.0,92.0,138.0,51.0,59.0,34.0,68.0,46.0,82.0,42.0
10,SAN LUIS POTOSI,43.0,41.0,17.0,12.0,39.0,1.0,5.0,37.0,34.0,...,14.0,48.0,54.0,43.0,15.0,14.0,24.0,28.0,35.0,16.0
11,SINALOA,36.0,37.0,35.0,28.0,58.0,42.0,83.0,30.0,64.0,...,39.0,69.0,72.0,61.0,46.0,45.0,80.0,65.0,80.0,47.0
12,TAMAULIPAS,73.0,54.0,19.0,22.0,40.0,9.0,18.0,54.0,63.0,...,17.0,78.0,86.0,39.0,78.0,65.0,52.0,56.0,63.0,52.0
13,VERACRUZ DE IGNACIO DE LA LLAVE,77.0,68.0,28.0,14.0,43.0,15.0,10.0,49.0,87.0,...,46.0,114.0,131.0,83.0,39.0,58.0,54.0,44.0,46.0,44.0
14,ZACATECAS,35.0,22.0,18.0,9.0,30.0,1.0,12.0,23.0,35.0,...,77.0,38.0,38.0,37.0,0.0,0.0,20.0,6.0,20.0,0.0

In [ ]:

import json, math, os

def df_to_records(df):
    """Convierte un DataFrame a lista de dicts serializable en JSON."""
    records = []
    for row in df.to_dict(orient="records"):
        clean = {}
        for k, v in row.items():
            if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):
                clean[k] = None
            elif hasattr(v, "item"):          # numpy scalar → Python nativo
                clean[k] = v.item()
            else:
                clean[k] = v
        records.append(clean)
    return records

payload = {
    "fetchedAt": pd.Timestamp.now().isoformat(),
    "baseAn":        df_to_records(base_an),
    "resultado":     df_to_records(resultado),
    "resumen":       df_to_records(resumen),
    "resumenEntidad": df_to_records(resumen_entidad),
}

out_path = os.path.join(os.path.dirname(os.path.abspath("__file__")), "public", "data.json")
os.makedirs(os.path.dirname(out_path), exist_ok=True)

with open(out_path, "w", encoding="utf-8") as f:
    json.dump(payload, f, ensure_ascii=False, default=str)

print(f"✓ data.json exportado → {out_path}")
print(f"  baseAn:        {len(payload['baseAn'])} filas")
print(f"  resultado:     {len(payload['resultado'])} filas")
print(f"  resumen:       {len(payload['resumen'])} filas")
print(f"  resumenEntidad:{len(payload['resumenEntidad'])} filas")